version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::241533132797:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-vAzQR1JWjvUW"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::241533132797:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-T5ThhiwnZXAO"
cloudformation_execution_role = "arn:aws:iam::241533132797:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-IrXu5IYBIjrL"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-czs8u5va4g9t"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::241533132797:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-tPy48HvEaqAL"
cloudformation_execution_role = "arn:aws:iam::241533132797:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-4jEvsuNg7S5A"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-hmwhjefjfk1t"
image_repository = ""
region = "us-east-1"
